### ISSUE TITLE
First issue ;-)

### ISSUE THREAD

**Issue by fgeorgatos** [mfelice/imeasure#1]
Hi,

for my interest: is there a metric which defines which kind of grammatical corrections would permit maximum compressibility? (think of wikipedia level of size). You might have some insight in this. tia, F.

**Comment by mfelice** [comment]
Hello,

I am not sure I have interpreted your question correctly. Do you mean a way of measuring how much we can compress a text in terms of valid shorter phrase replacements? If that is what you mean, I am not aware of such work.
M.
